// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbvPrerw124g3vrVhfnCK3CB3169Tfav8',
    appId: '1:196540797311:android:bbc0ed269a6482e5ca8a4a',
    messagingSenderId: '196540797311',
    projectId: 'final-year-project-6e3f4',
    storageBucket: 'final-year-project-6e3f4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu-qjaT69t7TC8eL-oqGH18-NqDzrt9C8',
    appId: '1:196540797311:ios:3cb46b771d8162b1ca8a4a',
    messagingSenderId: '196540797311',
    projectId: 'final-year-project-6e3f4',
    storageBucket: 'final-year-project-6e3f4.firebasestorage.app',
    iosBundleId: 'com.example.finalYearProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC56QoMwt1TKdehTRO5JRhd3RbtpCazV5k',
    appId: '1:196540797311:web:dd684f64e49fdab8ca8a4a',
    messagingSenderId: '196540797311',
    projectId: 'final-year-project-6e3f4',
    authDomain: 'final-year-project-6e3f4.firebaseapp.com',
    storageBucket: 'final-year-project-6e3f4.firebasestorage.app',
  );
}
